export const Questions = [
  {
    prompt: "1. Information technology (IT) is the use of computers to __________ data and information.",
    optionA: "store",
    optionB: "retrieve",
    optionC: "store or retrieve",
    optionD: "None of the above",
    asnwer: "optionD",
  },
  {
    prompt: "2. IT is considered to be a subset of?",
    optionA: "IST",
    optionB: "ICT",
    optionC: "IDT",
    optionD: "IOT",
    asnwer: "optionB",
  },
  {
    prompt: "3. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "4. Data transmission has _________ aspects.",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    asnwer: "optionC",
  },
  {
    prompt: "5. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "6. Information technology (IT) is the use of computers to __________ data and information.",
    optionA: "store",
    optionB: "retrieve",
    optionC: "store or retrieve",
    optionD: "None of the above",
    asnwer: "optionD",
  },
  {
    prompt: "7. IT is considered to be a subset of?",
    optionA: "IST",
    optionB: "ICT",
    optionC: "IDT",
    optionD: "IOT",
    asnwer: "optionB",
  },
  {
    prompt: "8. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "9. Data transmission has _________ aspects.",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    asnwer: "optionC",
  },
  {
    prompt: "10. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "11. Information technology (IT) is the use of computers to __________ data and information.",
    optionA: "store",
    optionB: "retrieve",
    optionC: "store or retrieve",
    optionD: "None of the above",
    asnwer: "optionD",
  },
  {
    prompt: "12. IT is considered to be a subset of?",
    optionA: "IST",
    optionB: "ICT",
    optionC: "IDT",
    optionD: "IOT",
    asnwer: "optionB",
  },
  {
    prompt: "13. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "14. Data transmission has _________ aspects.",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    asnwer: "optionC",
  },
  {
    prompt: "15. Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
];
